### ISSUE TITLE
react-load-script@0.0.6: abandoned and unmaintained

### ISSUE THREAD

**Issue by trevorh** [feathery-org/feathery-react#1157]
Hi,

We get an npm warning:
> `npm WARN deprecated react-load-script@0.0.6: abandoned and unmaintained` about `react-load-script`

for the React SDK. 

The package is included [here](https://github.com/feathery-org/feathery-react/blob/3bf9a5e7defcb53809e56d9505634cb1e115bf59/package.json#L107).

Are there plans to find an alternative?

Thanks!
Trevor

**Comment by bo-dun-1** [comment]
actually we moved away from it a while back, we've gone ahead and removed it from 2.0.407
